# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed7b4377f763cf444cea5eebe735fc10a168f13b820924c1f5051525720fec22f999710cd5ea26a24cb7f259445ecc9e10b4962ea9f08472a620730158cd7ff4

test:
  secret_key_base: 5a6edda0e20a9537ea0c30be62e842fe3e2e1d9bad171fc74ca48922bb1d54ac162439da8818d6ceaffb5f3f4d10fb5e5ede95ea976602411a15d29d35d72c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
